import type { DictEntry } from "./literacy-types";

export const SEED_DICT: DictEntry[] = [
  {
    id: 1,
    word: "스타벅스 가야지",
    student_definition: "스타벅스가 5.18 관련 행사(탱크데이)를 했다는 허위 사실과 결합하여, 광주 지역과 5.18 민주화운동의 희생자들을 조롱하기 위해 사용된 심각한 지역 비하 혐오 표현",
    suggested_by: "교사 프리셋",
    source: "온라인 커뮤니티 및 학생 야구 비하 논란",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 5, grammar_destruction: 1 },
    total_harmful_score: 84,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["바른 표현 사용", "역사적 사실 존중"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 2,
    word: "탱크데이",
    student_definition: "5.18 민주화운동 당시 계엄군의 탱크 진압을 희화화하고 희생자들을 모욕하기 위해 만들어진 반인륜적 은어",
    suggested_by: "교사 프리셋",
    source: "일간베스트 등 극우 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 5, grammar_destruction: 2 },
    total_harmful_score: 88,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["5.18 민주화운동", "역사적 아픔 공감"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 3,
    word: "운지",
    student_definition: "특정 전임 대통령의 서거를 비하하고 조롱하기 위해 만들어진 대표적인 일베 발 혐오 신조어",
    suggested_by: "교사 프리셋",
    source: "일간베스트 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 4, grammar_destruction: 3 },
    total_harmful_score: 88,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["추락하다", "떨어지다"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 4,
    word: "홍어",
    student_definition: "호남 지역 주민들을 특정 수산물에 빗대어 비하하고 차별하기 위해 사용하는 악의적인 지역 혐오 단어",
    suggested_by: "교사 프리셋",
    source: "일간베스트 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 2, grammar_destruction: 1 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["호남 지역민", "차별 없는 언어 사용"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 5,
    word: "이기야",
    student_definition: "영남 지역 방언을 왜곡하여 특정 정치인을 조롱하고 커뮤니티 소속감을 드러내기 위해 사용하는 혐오 코드 어미",
    suggested_by: "교사 프리셋",
    source: "일간베스트 커뮤니티",
    evaluations: { aggression: 4, bullying: 3, discrimination: 5, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["표준어 어미 사용", "~이구나"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 6,
    word: "노노체 (~노)",
    student_definition: "문맥에 맞지 않게 끝에 '노'를 붙여 특정 대상을 풍자하는 일베의 대표적인 조롱성 말투",
    suggested_by: "교사 프리셋",
    source: "일간베스트 커뮤니티",
    evaluations: { aggression: 3, bullying: 3, discrimination: 5, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["~했니?", "~했어?"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 7,
    word: "누칼협",
    student_definition: "누가 칼 들고 협박함의 줄임말로, 타인의 힘든 상황에 공감하지 않고 조롱하는 차가운 매체 언어",
    suggested_by: "교사 프리셋",
    source: "온라인 게임 커뮤니티",
    evaluations: { aggression: 5, bullying: 4, discrimination: 2, violence: 4, grammar_destruction: 4 },
    total_harmful_score: 76,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["많이 힘들었겠구나", "속상하겠다"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 8,
    word: "알빠노",
    student_definition: "내가 알 바 아니라는 뜻에 일베식 어미를 붙여 타인의 고통에 극단적으로 무관심을 표하는 언어",
    suggested_by: "교사 프리셋",
    source: "인터넷 방송",
    evaluations: { aggression: 4, bullying: 4, discrimination: 4, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["상관없어", "내 관여 밖의 일이야"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 9,
    word: "피싸개",
    student_definition: "여성의 생리 현상을 비하하고 여성 전체에 대한 극단적 혐오를 드러내는 폭력적인 차별 용어",
    suggested_by: "교사 프리셋",
    source: "남초 온라인 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 3, grammar_destruction: 2 },
    total_harmful_score: 80,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["여성", "양성평등 언어 사용"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 10,
    word: "한남 / 한녀",
    student_definition: "한국 남성/여성을 벌레 등에 빗대어 성별 간의 혐오와 대립을 조장하는 차별적 비하 발언",
    suggested_by: "교사 프리셋",
    source: "성별 갈등 커뮤니티",
    evaluations: { aggression: 4, bullying: 4, discrimination: 5, violence: 2, grammar_destruction: 2 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["한국 남성", "한국 여성"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 11,
    word: "틀딱",
    student_definition: "노인들의 틀니 소리를 빗대어 고령층을 혐오하고 세대 갈등을 유발하는 노인 비하 단어",
    suggested_by: "교사 프리셋",
    source: "온라인 커뮤니티",
    evaluations: { aggression: 5, bullying: 4, discrimination: 5, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["어르신", "노인"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 12,
    word: "맘충",
    student_definition: "아이를 키우는 어머니들을 벌레에 빗대어 비하하고 혐오하는 차별적 조롱 표현",
    suggested_by: "교사 프리셋",
    source: "온라인 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["어머니", "학부모"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 13,
    word: "잼민이",
    student_definition: "어린이나 초등학생이 공공예절을 지키지 않는다는 편견을 씌워 연령층을 비하하는 단어",
    suggested_by: "교사 프리셋",
    source: "인터넷 방송",
    evaluations: { aggression: 3, bullying: 4, discrimination: 4, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 60,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["어린이", "초등학생"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 14,
    word: "퐁퐁남",
    student_definition: "결혼 생활을 하는 남성을 경제적 착취의 피해자로 규정하며 여성 혐오적 시각을 드러내는 단어",
    suggested_by: "교사 프리셋",
    source: "남초 온라인 커뮤니티",
    evaluations: { aggression: 4, bullying: 4, discrimination: 5, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 64,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["기혼 남성", "남편"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 15,
    word: "어쩔티비",
    student_definition: "상대방의 의견이나 조언을 무시하고 대화를 단절시키기 위해 사용하는 예의 없는 유행어",
    suggested_by: "교사 프리셋",
    source: "유튜브 콘텐츠",
    evaluations: { aggression: 4, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 56,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["그렇구나", "내 생각은 달라"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 16,
    word: "핑프",
    student_definition: "스스로 검색하지 않고 남에게 의존하는 사람을 조롱하여 무안을 주는 공격적 표현",
    suggested_by: "교사 프리셋",
    source: "대학 및 커뮤니티 게시판",
    evaluations: { aggression: 3, bullying: 4, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 52,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["의존적인 습관", "스스로 찾아보기"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 17,
    word: "킹받네",
    student_definition: "화가 나거나 어이없는 상황을 문법을 파괴하여 자극적으로 표현하는 일상 속 비속어",
    suggested_by: "교사 프리셋",
    source: "인터넷 방송",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 화가 나", "어처구니가 없어"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 18,
    word: "개이득",
    student_definition: "접두사 개-를 남용하여 큰 이익을 보았음을 강조하는 상스러운 문법 파괴 표현",
    suggested_by: "교사 프리셋",
    source: "온라인 커뮤니티",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["큰 이익이야", "정말 잘됐어"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 19,
    word: "중꺾마",
    student_definition: "중요한 것은 꺾이지 않는 마음의 줄임말로 긍정적 의미이나, 과도한 줄임말 사용에 해당함",
    suggested_by: "교사 프리셋",
    source: "e스포츠 보도",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["포기하지 않는 마음", "끈기"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 20,
    word: "혜자스럽다",
    student_definition: "가성비가 훌륭하다는 의미로 특정 인물의 이름을 차용하여 만들어진 신조어",
    suggested_by: "교사 프리셋",
    source: "편의점 상품 밈",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["가격 대비 성능이 좋다", "푸짐하다"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 21,
    word: "쿠쿠루삥뽕",
    student_definition: "상대방을 약 올리고 비웃기 위해 사용하는 아무 의미 없는 의성어 밈으로, 대화의 예절을 심각하게 훼손하는 무시성 표현",
    suggested_by: "교사 프리셋",
    source: "트위치 도네이션 TTS 유행어",
    evaluations: { aggression: 4, bullying: 4, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 60,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["놀리지 말자", "바른 말로 대화하자"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 22,
    word: "억까 / 억빠",
    student_definition: "'억지로 까기(비난)'와 '억지로 빨기(칭찬)'의 줄임말로, 객관적인 사실과 관계없이 무조건적으로 상대를 비난하거나 맹신할 때 쓰는 말",
    suggested_by: "교사 프리셋",
    source: "인터넷 게임 방송 및 커뮤니티",
    evaluations: { aggression: 4, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 52,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["근거 없는 비난", "과도한 칭찬", "사실대로 말하기"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 23,
    word: "삼일한",
    student_definition: "'여자는 3일에 한 번씩 때려야 한다'라는 뜻을 가진 극단적인 여성 혐오이자 폭력 예찬성 범죄적 은어",
    suggested_by: "교사 프리셋",
    source: "일간베스트 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 5, grammar_destruction: 2 },
    total_harmful_score: 88,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["사용 절대 금지", "양성평등 사상 존중"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 24,
    word: "김치녀 / 스시녀",
    student_definition: "한국 여성을 특정 음식에 빗대어 허영심이 많다고 비하하는 반면, 외국 여성을 지나치게 환상화하여 성별·국가 간 차별을 조장하는 단어",
    suggested_by: "교사 프리셋",
    source: "남초 온라인 커뮤니티",
    evaluations: { aggression: 4, bullying: 3, discrimination: 5, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 60,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["한국 여성", "외국 여성", "올바른 명칭 사용"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 25,
    word: "한남충",
    student_definition: "한국 남성에 벌레 충(蟲) 자를 결합하여, 남성 집단 전체를 무분별하게 비하하고 혐오하는 차별적 표현",
    suggested_by: "교사 프리셋",
    source: "여초 온라인 커뮤니티",
    evaluations: { aggression: 5, bullying: 4, discrimination: 5, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["한국 남성", "서로 존중하는 표현"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 26,
    word: "개지리네",
    student_definition: "너무 엄청나거나 놀랍다는 뜻을 저속하게 표현한 비속어로, 생리적인 현상에 비유하여 품위를 떨어뜨리는 말",
    suggested_by: "교사 프리셋",
    source: "인터넷 게임 및 스트리밍 댓글",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 대단하다", "굉장히 놀랍다"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 27,
    word: "뇌절",
    student_definition: "똑같은 말이나 행동을 분위기에 맞지 않게 계속 반복하여 상대방에게 지루함과 짜증을 유발하는 태도를 가리키는 비속어",
    suggested_by: "교사 프리셋",
    source: "온라인 만화 커뮤니티 및 게임 밈",
    evaluations: { aggression: 3, bullying: 3, discrimination: 1, violence: 2, grammar_destruction: 4 },
    total_harmful_score: 52,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["과도한 반복", "그만하기", "적당히 하기"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 28,
    word: "능지처참 / 능지",
    student_definition: "과거 잔인한 사형 방식의 이름을 빌려와 상대방의 지능이나 판단력을 심각하게 비하하고 모욕할 때 사용하는 폭력적인 언어",
    suggested_by: "교사 프리셋",
    source: "인터넷 커뮤니티 및 악성 댓글",
    evaluations: { aggression: 5, bullying: 4, discrimination: 1, violence: 5, grammar_destruction: 3 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["지능", "생각이 부족하다", "생각의 차이"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 29,
    word: "잼민펀치",
    student_definition: "초등학생이나 어린아이들의 서툴고 약한 주먹다짐을 놀리기 위해 쓰는 말로, 특정 연령층을 희화화하고 무시하는 태도가 깔린 밈",
    suggested_by: "교사 프리셋",
    source: "유튜브 및 숏폼 챌린지 밈",
    evaluations: { aggression: 3, bullying: 4, discrimination: 3, violence: 2, grammar_destruction: 4 },
    total_harmful_score: 64,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["약한 장난", "어린이들의 장난"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 30,
    word: "갓생",
    student_definition: "신을 뜻하는 '갓(God)'과 '인생'을 합쳐 하루하루 계획적으로 열심히 살아가는 긍정적인 삶의 태도를 뜻하는 유행어",
    suggested_by: "교사 프리셋",
    source: "갓생 살기 챌린지 및 SNS 유행어",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["보람찬 생활", "성실한 삶", "열심히 살기"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 31,
    word: "까보전",
    student_definition: "'까고 보면 전라도'의 줄임말로, 부정적인 사건이 발생했을 때 근거 없이 특정 호남 지역을 표적 삼아 혐오하고 차별하는 심각한 일베 밈",
    suggested_by: "교사 프리셋",
    source: "일간베스트 등 지역 비하 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 80,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["지역 차별 금지", "편견 없는 언어"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 32,
    word: "네다홍",
    student_definition: "'네, 다음 홍어'의 줄임말로 타인의 의견에 반박하지 못할 때 무조건 호남 지역 주민으로 몰아가며 입을 막고 비하하는 반사회적 조롱 표현",
    suggested_by: "교사 프리셋",
    source: "일간베스트 커뮤니티",
    evaluations: { aggression: 5, bullying: 4, discrimination: 5, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 76,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["의견을 존중하자", "비하 발언 멈추기"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 33,
    word: "스댕 / 스뎅",
    student_definition: "행동이 어리숙하거나 비정상적인 사람을 은근히 지적하고 따돌리는 조롱조의 유행 신조어",
    suggested_by: "교사 프리셋",
    source: "유튜브 및 숏폼 무개념 행동 영상 댓글",
    evaluations: { aggression: 4, bullying: 4, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 56,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["서툰 행동", "배려하는 말투 사용"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 34,
    word: "개안습",
    student_definition: "'안구에 습기 차다(눈물 난다)'에 비속어 접두사를 붙인 표현으로, 상대방의 딱하거나 초라한 상황을 가볍게 웃음거리로 만들 때 쓰는 어휘",
    suggested_by: "교사 프리셋",
    source: "과거 예능 프로그램 및 인터넷 유행어",
    evaluations: { aggression: 2, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 44,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["안타깝다", "눈물이 나네", "슬픈 상황이야"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 35,
    word: "갑분싸",
    student_definition: "'갑자기 분위기가 싸해진다'의 줄임말로, 말실수를 하거나 재미없는 이야기를 한 친구에게 면박을 주어 소외감을 느끼게 만드는 신조어",
    suggested_by: "교사 프리셋",
    source: "방송 자막 및 인터넷 커뮤니티",
    evaluations: { aggression: 3, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["분위기가 차가워졌어", "이야기를 이어나가자"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 36,
    word: "혜자 / 창렬",
    student_definition: "내용물이 푸짐한 것과 부실한 것을 특정인의 이름으로 극단화하여 비교하는 표현으로, 타인의 실명을 부정적 대명사로 낙인찍는 부적절한 언어 밈",
    suggested_by: "교사 프리셋",
    source: "특정 연예인 이름 차용 식품 유래 밈",
    evaluations: { aggression: 3, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["푸짐하다 / 부실하다", "양에 비해 비싸다"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 37,
    word: "발컨",
    student_definition: "'발로 컨트롤(조작)한다'의 줄임말로, 함께 게임을 하는 팀원이나 상대방의 실력이 형편없음을 조롱하고 면박 주는 비하 표현",
    suggested_by: "교사 프리셋",
    source: "온라인 대전 게임 대화창",
    evaluations: { aggression: 4, bullying: 4, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 56,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["조작이 서툴다", "게임 실력이 아쉽다", "연습해보자"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 38,
    word: "국룰",
    student_definition: "'국민 룰(규칙)'의 줄임말로 사회적인 상식이나 당연하게 굳어진 보편적 행동 양식을 가볍게 부르는 유행 어휘",
    suggested_by: "교사 프리셋",
    source: "예능 자막 및 일상 신조어",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["보편적인 규칙", "상식적인 행동", "기본 규칙"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 39,
    word: "소확행",
    student_definition: "'소소하지만 확실한 행복'의 줄임말로 거창하지 않은 일상 속 작은 즐거움을 즐기려는 태도를 뜻하는 고운 유행 신조어",
    suggested_by: "교사 프리셋",
    source: "트렌드 도서 및 에세이 유행어",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["작은 행복", "소소한 즐거움"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 40,
    word: "어가돈 (어차피 가해자는 돈)",
    student_definition: "학교폭력 청문회나 법적 분쟁을 보며 '어차피 돈이 많으면 처벌을 피한다'는 식으로 사법 불신과 배금주의를 조장하는 씁쓸한 온라인 유행어",
    suggested_by: "교사 프리셋",
    source: "드라마 및 학교폭력 관련 뉴스 댓글 밈",
    evaluations: { aggression: 3, bullying: 3, discrimination: 2, violence: 3, grammar_destruction: 4 },
    total_harmful_score: 60,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["법과 정의를 믿자", "올바른 가치관 갖기"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:59:00",
  },
  {
    id: 41,
    word: "잼민이레이더",
    student_definition: "온라인 공간에서 미숙한 행동을 하거나 실수를 하는 유저를 무조건 초등학생으로 단정 짓고 색출하여 조롱하려는 배타적인 태도가 담긴 밈",
    suggested_by: "교사 프리셋",
    source: "유튜브 및 틱톡 게임 영상 자막 밈",
    evaluations: { aggression: 4, bullying: 4, discrimination: 4, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["서툰 행동 지적하지 않기", "편견 없이 대하기"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 42,
    word: "개념녀",
    student_definition: "여성이 지녀야 할 기준을 남성 중심적 시각에서 규정하고 이에 순응하는 사람만을 칭찬하며, 그렇지 않은 여성들을 은근히 비하하는 차별적 단어",
    suggested_by: "교사 프리셋",
    source: "인터넷 유머 게시판 및 남초 커뮤니티",
    evaluations: { aggression: 3, bullying: 3, discrimination: 5, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 56,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["바른 가치관을 가진 사람", "주관이 뚜렷한 사람"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 43,
    word: "메갈충",
    student_definition: "특정 여성주의 커뮤니티 이용자를 벌레에 빗대어 부르는 말로, 자신과 의견이 다른 여성 전체를 모욕하고 낙인찍기 위해 오남용되는 혐오 어휘",
    suggested_by: "교사 프리셋",
    source: "온라인 커뮤니티 및 댓글",
    evaluations: { aggression: 5, bullying: 4, discrimination: 5, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["비하 발언 자제", "서로 다른 의견 존중"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 44,
    word: "딸배",
    student_definition: "배달 대행업체 기사들을 '배달'의 글자를 뒤집어 비속하게 부르는 단어로, 특정 직업군 전체를 낮잡아보고 멸시하는 대표적인 직업 비하 표현",
    suggested_by: "교사 프리셋",
    source: "인터넷 커뮤니티 및 도로 교통 관련 유튜브",
    evaluations: { aggression: 5, bullying: 4, discrimination: 5, violence: 2, grammar_destruction: 4 },
    total_harmful_score: 80,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["배달 기사님", "배달원"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 45,
    word: "틀딱충",
    student_definition: "노인 비하 표현인 '틀딱'에 벌레 충(蟲) 자까지 결합하여, 사회 어르신들을 극단적으로 조롱하고 모욕하는 심각한 세대 혐오 표현",
    suggested_by: "교사 프리셋",
    source: "인터넷 기사 댓글 및 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 76,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["어르신", "노년층 어른"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 46,
    word: "개웃기네",
    student_definition: "정말 재미있거나 웃기다는 뜻을 강조하기 위해 접두사 '개-'를 무분별하게 붙여 사용하는 저속한 유행 문법",
    suggested_by: "교사 프리셋",
    source: "청소년 일상 대화 및 온라인 채팅",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 재미있다", "무척 웃기다"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 47,
    word: "시강",
    student_definition: "'시선 강탈'의 줄임말로, 눈길을 확 사로잡을 만큼 매력적이거나 눈에 띄는 대상을 가리키는 일반적인 신조 축약어",
    suggested_by: "교사 프리셋",
    source: "방송 예능 자막 및 일상 신조어",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["시선을 사로잡음", "눈길을 끎"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 48,
    word: "박박 / 짜짜",
    student_definition: "강조를 뜻하는 '대박'을 '박박'으로, '진짜'를 '짜짜'로 변형하여 쓰는 무분별한 말장난 형태의 한글 파괴적 유행어",
    suggested_by: "교as 프리셋",
    source: "여고생 일상 유행어 및 SNS 문맥",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["대박", "진짜", "정말로"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 49,
    word: "기레기",
    student_definition: "기자와 쓰레기를 합성한 말로, 자극적이거나 왜곡된 보도를 하는 언론인을 비판하려는 목적이나, 직업군 전체를 모욕하는 비속어로 오용되기도 함",
    suggested_by: "교사 프리셋",
    source: "포털 뉴스 댓글 및 사회 신조어",
    evaluations: { aggression: 4, bullying: 3, discrimination: 4, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 64,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["부정확한 언론", "무책임한 기자"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 50,
    word: "찐따 / 찐",
    student_definition: "또래 집단에서 어울리지 못하고 소외된 친구를 대놓고 무안 주거나 놀릴 때 사용하는 은어로, 집단 따돌림을 유발하는 대표적인 악성 단어",
    suggested_by: "교사 프리셋",
    source: "학교 교실 및 온라인 단톡방",
    evaluations: { aggression: 5, bullying: 5, discrimination: 2, violence: 2, grammar_destruction: 3 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["서툰 친구", "배려가 필요한 친구"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 51,
    word: "안물안궁",
    student_definition: "'안 물어봤고 안 궁금해'의 줄임말로, 친구가 진지하게 의견을 말할 때 대화를 강제로 끊고 무시하여 정서적 상처를 주는 배려 없는 대화 차단어",
    suggested_by: "교사 프리셋",
    source: "초등학생 일상 어휘 및 웹툰 댓글",
    evaluations: { aggression: 4, bullying: 4, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 56,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["그렇구나", "처음 알게 된 사실이야"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 52,
    word: "가성비갑",
    student_definition: "가격 대비 성능이나 효율이 최고라는 뜻을 한자 '갑(甲)'을 강조의 접미사처럼 결합하여 표현한 대중적인 상업성 유행어",
    suggested_by: "교사 프리셋",
    source: "인터넷 쇼핑 후기 및 일상 밈",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["가성비가 아주 좋다", "효율성이 뛰어나다"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 53,
    word: "TMI",
    student_definition: "'Too Much Information'의 줄임말로, 굳이 알 필요가 없는 너무 과도하고 자잘한 개인 정보를 말하는 상황을 유쾌하게 지적하는 신조어",
    suggested_by: "교사 프리셋",
    source: "해외 SNS 및 일상 대화 유행어",
    evaluations: { aggression: 2, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["과도한 정보", "불필요한 이야기"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 54,
    word: "연서복",
    student_definition: "'연애에 서툰 복학생'의 줄임말로, 눈치 없이 이성에게 과도한 호감을 표하는 특정 집단이나 선배를 유머의 소재로 삼아 비꼬는 단어",
    suggested_by: "교사 프리셋",
    source: "트위터 만화 밈 및 대학교 커뮤니티",
    evaluations: { aggression: 3, bullying: 3, discrimination: 2, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 52,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["서툰 태도", "눈치가 없는 사람"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 55,
    word: "순살",
    student_definition: "뼈 없는 치킨 메뉴 이름에서 유래하여 철근이 빠진 부실 건축물을 조롱하는 말이나, 일상에서 팩트로 뼈를 맞았다는 뜻의 '뼈때리네'의 심화형 비속 밈",
    suggested_by: "교사 프리셋",
    source: "아파트 부실공사 뉴스 댓글 밈",
    evaluations: { aggression: 3, bullying: 3, discrimination: 1, violence: 2, grammar_destruction: 4 },
    total_harmful_score: 52,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["정곡을 찔림", "부실하게 지어짐"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 56,
    word: "주작",
    student_definition: "사실이 아닌 일을 가짜로 꾸며내어 남을 속이는 행동을 가리키는 은어로, 사기 행위나 거짓말을 은근히 유행어처럼 가볍게 표현하는 말",
    suggested_by: "교사 프리셋",
    source: "인터넷 방송 조작 논란 및 게임 커뮤니티",
    evaluations: { aggression: 3, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 44,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["조작", "거짓말", "꾸며낸 이야기"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 57,
    word: "피꺼솟",
    student_definition: "'피가 거꾸로 솟는다'의 줄임말로, 극도로 화가 나거나 억울한 감정을 신체 훼손적 상상을 자극하는 어휘로 과격하게 표현한 신조 축약어",
    suggested_by: "교사 프리셋",
    source: "웹툰 댓글 및 온라인 커뮤니티",
    evaluations: { aggression: 3, bullying: 1, discrimination: 1, violence: 4, grammar_destruction: 4 },
    total_harmful_score: 52,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["매우 화가 난다", "분통이 터진다"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 58,
    word: "솔까말",
    student_definition: "'솔직히 까놓고 말해서'의 줄임말로 자신의 의견을 필터링 없이 과감하게 전하겠다는 뜻을 품은 일상적인 긴 축약어",
    suggested_by: "교사 프리셋",
    source: "인터넷 채팅 및 예능 자막",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["솔직히 말하면", "솔직하게 표현해서"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 59,
    word: "인싸 / 아싸",
    student_definition: "집단 내부에서 잘 어울리는 '인사이더'와 겉도는 '아웃사이더'를 줄여 부르는 말로, 인간관계를 서열화하고 편을 가르는 문화를 조장하는 신조어",
    suggested_by: "교사 프리셋",
    source: "대학가 유행어 및 대중 매체",
    evaluations: { aggression: 3, bullying: 4, discrimination: 2, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 56,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["사교적인 사람 / 독립적인 사람", "외향형 / 내향형"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 60,
    word: "무지성",
    student_definition: "아무런 지성이나 논리적인 생각 없이 맹목적으로 행동하거나 남을 따라 하는 태도를 비하할 때 쓰는 어휘로, 상대의 지적 수준을 깎아내리는 비속어",
    suggested_by: "교사 프리셋",
    source: "애니메이션 커뮤니티 및 인터넷 주식 방송",
    evaluations: { aggression: 4, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 52,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["생각 없는 행동", "무조건적인 태도", "맹목적인 따라 하기"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:01:00",
  },
  {
    id: 61,
    word: "마라탕후루",
    student_definition: "특정 자극적인 음식을 결합한 중독성 있는 챌린지 가사에서 유래하여 일상에서 자주 쓰이나, 과도한 영양 불균형 소비를 조장하고 무분별한 반복 언어에 해당함",
    suggested_by: "교사 프리셋",
    source: "틱톡 및 숏폼 챌린지 음악 밈",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 32,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["좋아하는 음식", "유행하는 노래"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 62,
    word: "꽁꽁 얼어붙은 한강 위로",
    student_definition: "뉴스 기자의 멘트와 고양이 영상을 짜깁기한 숏폼 댄스 유행어로, 진지한 사회적 사실이나 보도를 가벼운 놀이문화로만 소비하는 매체 왜곡적 특징이 있음",
    suggested_by: "교사 프리셋",
    source: "뉴스 보도 인용 릴스 댄스 밈",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["추운 겨울 날씨", "유행하는 춤"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 63,
    word: "도파민 중독",
    student_definition: "자극적이고 재미있는 미디어 콘텐츠를 끊임없이 갈구하는 자신의 상태를 뜻하는 말로, 디지털 매체의 과의존 현상을 가볍게 희화화하는 신조 밈",
    suggested_by: "교사 프리셋",
    source: "인스타그램 및 숏폼 댓글 유행어",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 2, grammar_destruction: 3 },
    total_harmful_score: 32,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["스마트폰 과의존", "자극적인 영상에 빠짐"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 64,
    word: "디토합니다 / 디토",
    student_definition: "라틴어 'Ditto(동감)'에서 유래하여 상대방의 의견에 전적으로 동의하고 공감할 때 쓰는 최신 SNS식 세련된 축약 어휘",
    suggested_by: "교사 프리셋",
    source: "아이돌 뮤직비디오 유래 릴스 댓글",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["나도 동감해", "전적으로 찬성해"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 65,
    word: "폼 미쳤다",
    student_definition: "기량이나 실력, 솜씨가 최고조에 달해 아주 멋진 모습을 보일 때 극찬하는 최신 유행어로 일상적인 어휘 파괴 요소가 담겨 있음",
    suggested_by: "교사 프리셋",
    source: "인터넷 스포츠 중계 및 숏폼 댓글",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 32,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["실력이 대단하다", "아주 멋진 모습이다"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 66,
    word: "T발 너 C야?",
    student_definition: "공감 능력이 부족한 이성적(T)인 사람을 저속한 욕설 발음(시발, 년)과 교묘하게 유사하도록 변형하여 상대를 무안 주고 낙인찍는 은근히 유해한 밈",
    suggested_by: "교사 프리셋",
    source: "MBTI 성향 평가 유래 숏폼 영상 밈",
    evaluations: { aggression: 5, bullying: 4, discrimination: 3, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["너는 무척 이성적이구나", "내 마음에 공감해 줘"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 67,
    word: "오히려 좋아",
    student_definition: "실패하거나 원치 않는 악조건 상황을 긍정적인 생각과 재치로 극복하려는 숏폼 속 대표적인 마인드셋 유행어",
    suggested_by: "교사 프리셋",
    source: "인터넷 개인 방송 및 인스타 툰",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 24,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["차라리 잘됐다", "오히려 긍정적인 기회야"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 68,
    word: "영까 / 올까",
    student_definition: "'영(Young)한 꼰대'와 '올드(Old)한 꼰대'의 줄임말로, 직장이나 학교 내에서 조언을 해주는 선배나 교사를 세대별로 조롱하고 편 가르는 밈",
    suggested_by: "교사 프리셋",
    source: "시사 트렌드 및 SNS 세대 갈등 용어",
    evaluations: { aggression: 4, bullying: 3, discrimination: 4, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 64,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["잔소리가 심한 사람", "생각이 굳은 선배"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 69,
    word: "스우파 / 스맨파 말투",
    student_definition: "방송 출연진의 거칠고 위협적인 댄서 특유의 톤과 신경질적인 말투를 따라 하는 밈으로, 일상 대화에서 공격성을 높일 우려가 있음",
    suggested_by: "교사 프리셋",
    source: "댄스 서바이벌 방송 릴스 패러디",
    evaluations: { aggression: 4, bullying: 3, discrimination: 1, violence: 2, grammar_destruction: 4 },
    total_harmful_score: 56,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["자신감 넘치는 말투", "부드러운 대화 톤"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 70,
    word: "삼점사점오 (3.4.5)",
    student_definition: "특정 학교폭력 가해 사건이나 고발 피해자의 고통을 가벼운 숫자 암호처럼 만들어 조롱하고 가십거리로 소비하는 대단히 악질적인 최신 매체 밈",
    suggested_by: "교사 프리셋",
    source: "초등학생 틱톡 학폭 피해 조롱 댓글",
    evaluations: { aggression: 5, bullying: 5, discrimination: 2, violence: 4, grammar_destruction: 4 },
    total_harmful_score: 80,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["피해자에게 공감하기", "장난조로 소비하지 않기"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 71,
    word: "홍박사님을 아세요?",
    student_definition: "특정 개그맨의 성인용 개그 노래와 춤에서 유래한 챌린지로, 초등학생들이 숨은 성적 비유나 선정적인 의미를 알지 못하고 무분별하게 따라 하여 유해함",
    suggested_by: "교사 프리셋",
    source: "틱톡 및 유튜브 숏폼 성인 유행어 챌린지",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["어린이에 맞는 춤", "건전한 유행어"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 72,
    word: "긁? / 긁혔네",
    student_definition: "'마음에 상처를 입었다', '자존심 상했다'라는 뜻을 자극적으로 표현한 최신 한 글자 조롱 밈으로, 상대방의 약점을 후벼파서 화를 돋우려는 의도가 강함",
    suggested_by: "교사 프리셋",
    source: "온라인 대전 게임 및 인스타그램 댓글",
    evaluations: { aggression: 5, bullying: 4, discrimination: 1, violence: 2, grammar_destruction: 5 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["자존심 상했구나", "속상하게 해서 미안해"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 73,
    word: "스불재",
    student_definition: "'스스로 불러온 재앙'의 줄임말로, 자신이 자초한 힘든 상황이나 과도한 스케줄을 재치 있고 자조적으로 한탄할 때 쓰는 신조 축약어",
    suggested_by: "교사 프리셋",
    source: "트위터 및 SNS 일상 밈",
    evaluations: { aggression: 1, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["내가 자초한 일이야", "스스로 만든 힘든 상황"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 74,
    word: "너 당황했지?",
    student_definition: "상대방이 말문이 막히거나 당황한 기색을 보일 때 끝까지 몰아붙이며 우위를 점하고 놀리기 위해 쓰는 메신저 공격형 밈",
    suggested_by: "교사 프리셋",
    source: "숏폼 애니메이션 유행 대사 밈",
    evaluations: { aggression: 4, bullying: 4, discrimination: 1, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["많이 당황스럽겠구나", "천천히 말해도 돼"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 75,
    word: "갓반인",
    student_definition: "신을 뜻하는 '갓(God)'과 일반인의 합성어로, 유명 연예인이 아닌 평범한 일반인 중 외모나 능력이 아주 뛰어난 사람을 동경하며 급을 나누는 신조어",
    suggested_by: "교사 프리셋",
    source: "아이돌 팬덤 SNS 및 인스타그램",
    evaluations: { aggression: 1, bullying: 1, discrimination: 3, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["멋진 일반인", "대단한 평범한 사람"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 76,
    word: "오운완",
    student_definition: "'오늘 운동 완료'의 줄임말로, 매일 성실하게 건강을 관리하는 자신의 모습을 사진과 함께 인증하는 최근의 건강하고 긍정적인 유행 태그",
    suggested_by: "교사 프리셋",
    source: "인스타그램 헬스/운동 인증 태그 밈",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["오늘 운동을 다 마쳤어", "성실한 운동 습관"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 77,
    word: "스멀스멀",
    student_definition: "어떤 유행이나 나쁜 버릇이 교실 속에 '스멀스멀' 기어 들어온다는 표현을 자막화한 유행 어휘로 일상에서 과도하게 반복 소비됨",
    suggested_by: "교사 프리셋",
    source: "유튜브 쇼츠 자막 및 댓글 효과음 밈",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 24,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["조금씩 퍼지는 모양", "점차 나타남"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 78,
    word: "아무 말 대잔치",
    student_definition: "논리나 맥락 없이 떠오르는 대로 생각나는 단어들을 마구 내뱉는 현상을 비유한 신조어로, 진지한 토론이나 국어 수업 대화를 방해할 우려가 있음",
    suggested_by: "교사 프리셋",
    source: "예능 자막 및 인스타 방송 댓글",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["맥락 없는 이야기", "생각나는 대로 말하기"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 79,
    word: "~에 미친 자",
    student_definition: "자신이 특정 취미나 공부, 음식에 깊게 몰두하고 있음을 '미치다'라는 과격하고 자극적인 단어로 연출하여 과장하는 SNS식 자극 표현",
    suggested_by: "교사 프리셋",
    source: "인스타그램 및 릴스 프로필 자막",
    evaluations: { aggression: 3, bullying: 1, discrimination: 1, violence: 3, grammar_destruction: 4 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["~를 아주 좋아하는 사람", "모두가 인정하는 전문가"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 80,
    word: "팩폭 / 팩트 폭행",
    student_definition: "사실을 바탕으로 상대방의 정곡을 찔러 말문을 막히게 하는 행동으로, '폭행'이라는 단어를 가볍게 결합하여 언어적 폭력성을 무감각하게 수용하게 만드는 밈",
    suggested_by: "교사 프리셋",
    source: "인터넷 기사 댓글 및 청소년 유행어",
    evaluations: { aggression: 4, bullying: 3, discrimination: 1, violence: 4, grammar_destruction: 4 },
    total_harmful_score: 64,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["정곡을 찌르는 말", "사실 그대로 조언하기"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:02:00",
  },
  {
    id: 81,
    word: "갈치하다",
    student_definition: "'갈취하다'의 발음을 장난스럽게 변형하거나 생선 갈치에 빗대어 친구의 물건, 게임 아이템을 은근히 빼앗는 행동을 가볍게 부르는 은어",
    suggested_by: "교사 프리셋",
    source: "유튜브 숏폼 및 초등학생 일상 은어",
    evaluations: { aggression: 4, bullying: 4, discrimination: 1, violence: 3, grammar_destruction: 5 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["강제로 빼앗다", "물건을 탐내다"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 82,
    word: "정리정돈",
    student_definition: "마음에 들지 않는 특정 친구나 무리를 집단 내에서 따돌리고 서열화하여 '방을 정리한다'는 식으로 표현하는 교묘한 괴롭힘성 밈",
    suggested_by: "교사 프리셋",
    source: "인스타 릴스 및 학교폭력 저격 댓글 밈",
    evaluations: { aggression: 5, bullying: 5, discrimination: 2, violence: 2, grammar_destruction: 2 },
    total_harmful_score: 64,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["서로 화해하기", "편가르지 않기"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 83,
    word: "오저치고",
    student_definition: "'오늘 저녁 치킨 고(Go)?'의 줄임말로, 청소년들 사이에서 일상적인 약속을 극단적으로 축약하여 사용하는 문법 파괴적 유행어",
    suggested_by: "교사 프리셋",
    source: "초등학생 급식실 및 메신저 유행어",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["오늘 저녁에 치킨 먹을래?", "음식 같이 먹기"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 84,
    word: "발작버튼",
    student_definition: "상대방이 민감하게 반응하거나 화를 내는 특정 주제를 비유한 말로, 질병 증상(발작)을 가볍게 희화화하여 상대를 자극하려는 의도가 담김",
    suggested_by: "교사 프리셋",
    source: "인터넷 기사 댓글 및 온라인 커뮤니티",
    evaluations: { aggression: 4, bullying: 4, discrimination: 4, violence: 2, grammar_destruction: 4 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["민감한 부분", "가장 화가 나는 점", "약점"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 85,
    word: "실화냐",
    student_definition: "눈앞의 사실이 진짜인지 믿기지 않을 때 의문을 표하는 말이나, 일상에서 과도하게 모든 문장에 습관적으로 붙여 쓰는 대표적인 유행 말투",
    suggested_by: "교사 프리셋",
    source: "인터넷 개인 방송 자막 및 SNS",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 32,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 사실이야?", "진짜 일어난 일이니?"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 86,
    word: "의문의 1패",
    student_definition: "아무런 잘못이나 행동을 하지 않았음에도 다른 상황과 비교되어 은근히 굴욕을 당하거나 패배자가 되었음을 위트 있게 나타내는 유행 표현",
    suggested_by: "교사 프리셋",
    source: "예능 프로그램 자막 및 인터넷 뉴스 댓글",
    evaluations: { aggression: 2, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["뜻밖의 손해", "은연중에 비교당함"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 87,
    word: "졌잘싸",
    student_definition: "'졌지만 잘 싸웠다'의 줄임말로, 결과는 패배했으나 끝까지 최선을 다한 과정의 아름다움을 격려하는 비교적 고운 의미의 신조 축약어",
    suggested_by: "교사 프리셋",
    source: "스포츠 기사 타이틀 및 인터넷 중계",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["졌지만 최선을 다했어", "아름다운 패배"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 88,
    word: "뇌피셜",
    student_definition: "공식적인 근거(Official)가 아니라 오직 자신의 뇌(생각)에서 나온 주관적인 추측을 사실처럼 말하는 태도를 꼬집는 은어적 표현",
    suggested_by: "교사 프리셋",
    source: "인터넷 정보 공유 게시판 및 댓글",
    evaluations: { aggression: 3, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 44,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["개인적인 추측", "근거 없는 생각", "내 주관적 의견"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 89,
    word: "팩트 체크",
    student_definition: "어떤 주장의 사실 여부를 확인한다는 뜻으로, 친구들의 일상 대화에서 지나치게 상대방 말꼬리를 잡고 따지며 면박을 줄 때 오용되는 유행어",
    suggested_by: "교사 프리셋",
    source: "시사 뉴스 및 청소년 토론 밈",
    evaluations: { aggression: 3, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["사실 여부 확인", "정확한 내용 알아보기"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 90,
    word: "엄근진",
    student_definition: "'엄격, 근엄, 진지'의 줄임말로, 유연하게 넘어가도 될 가벼운 상황에서 지나치게 정색을 하거나 진지하게 반응하는 사람을 놀리는 단어",
    suggested_by: "교사 프리셋",
    source: "예능 자막 및 인스타그램 댓글",
    evaluations: { aggression: 2, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 44,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["매우 진지함", "엄격한 태도"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 91,
    word: "갑통알",
    student_definition: "'갑자기 통장을 보니 알바(아르바이트)를 해야겠다'의 줄임말로 용돈이 부족하거나 경제적 곤란을 겪는 상황을 자조하는 인터넷 신조어",
    suggested_by: "교사 프리셋",
    source: "청년 실업 관련 기사 및 SNS 밈",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 32,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["통장 잔고가 부족함", "돈을 저축해야겠어"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 92,
    word: "좋댓구알",
    student_definition: "'좋아요, 댓글, 구독, 알림 설정'의 앞 글자를 따온 말로, 발음이 욕설과 유사하게 들리도록 의도적으로 유도한 자극적이고 부적절한 축약어 밈",
    suggested_by: "교사 프리셋",
    source: "유튜브 크리에이터 멘트 엔딩 밈",
    evaluations: { aggression: 3, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 44,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["좋아요와 구독 부탁해요", "영상 추천"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 93,
    word: "의문의 1승",
    student_definition: "가만히 있었음에도 외부의 어부지리 상황 덕분에 이득을 보거나 상대적으로 우월한 위치에 서게 되었음을 표현하는 유행어",
    suggested_by: "교사 프리셋",
    source: "스포츠 유행어 파생 일상 밈",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["뜻밖의 이득", "가만히 얻은 승리"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 94,
    word: "순간포착",
    student_definition: "친구나 연예인의 이상한 표정이나 흑역사 순간을 절묘하게 캡처하여 놀리는 자막으로 또래 관계에서 조롱의 도구로 과도하게 쓰임",
    suggested_by: "교사 프리셋",
    source: "유튜브 숏폼 리액션 자막 밈",
    evaluations: { aggression: 3, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["찰나의 순간", "절묘한 사진"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 95,
    word: "세젤예 / 세젤귀",
    student_definition: "'세상에서 제일 예쁨', '세상에서 제일 귀여움'의 줄임말로 대상을 극찬하는 예쁜 의미이나 긴 문장을 과도하게 깨뜨려 쓰는 버릇에 해당함",
    suggested_by: "교사 프리셋",
    source: "육아 블로그 및 초등 여학생 유행어",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 32,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["세상에서 가장 예쁘다", "가장 귀엽다"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 96,
    word: "고답이",
    student_definition: "'고구마 먹은 것처럼 답답한 사람'의 줄임말로, 눈치가 없거나 상황 대처가 느린 주변 사람을 멸시하고 답답해하는 낙인성 신조어",
    suggested_by: "교사 프리셋",
    source: "웹소설 및 드라마 감상 댓글",
    evaluations: { aggression: 3, bullying: 4, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 52,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["행동이 신중한 사람", "답답한 상황", "느긋한 성격"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 97,
    word: "사이다",
    student_definition: "답답했던 상황이 탄산음료(사이다)를 마신 것처럼 속 시원하게 해결되는 모습을 비유한 긍정적 표현이나, 지나치게 공격적으로 상대를 몰아붙이는 독설을 옹호하는 밈으로 변질되기도 함",
    suggested_by: "교사 프리셋",
    source: "드라마 및 뉴스 평론 유행어",
    evaluations: { aggression: 3, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["속 시원한 해결", "명쾌한 답변"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 98,
    word: "심멎",
    student_definition: "'심장이 멎을 것 같다'의 줄임말로 대상이 너무 잘생기거나 아름다워 큰 충격을 받았음을 나타내나, 신체 마비 증상을 비유한 과격한 축약어",
    suggested_by: "교사 프리셋",
    source: "연예 미디어 보도 및 팬덤 SNS 밈",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 3, grammar_destruction: 4 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["가슴이 두근거려", "매우 아름다워"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 99,
    word: "취존",
    student_definition: "'취향 존중'의 줄임말로 서로의 서로 다른 취미와 호불호를 인정하자는 올바른 의도이나 단어가 가볍게 축약되어 널리 소모됨",
    suggested_by: "교사 프리셋",
    source: "취미 공유 온라인 커뮤니티",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["취향을 존중하다", "개인적 선호 인정"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 100,
    word: "개소리",
    student_definition: "상대방의 의견이나 논리가 전혀 터무니없고 가치 없음을 동물(개)의 소리에 비유하여 깎아내리는 대단히 모욕적이고 공격적인 비속어",
    suggested_by: "교사 프리셋",
    source: "웹툰 대사 및 실시간 유튜브 댓글",
    evaluations: { aggression: 5, bullying: 4, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 60,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["말도 안 되는 이야기", "잘못된 의견", "터무니없는 주장"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-11 00:04:00",
  },
  {
    id: 101,
    word: "야르",
    source: "나무위키 등재 최신 숏폼 및 Z세대 유행어",
    student_definition: "1990년대부터 쓰이던 감탄사가 최근 크리에이터들에 의해 재유행한 것으로, 기쁨이나 흥분을 나타내는 '앗싸, 나이스'의 뜻을 가진 단순 비격식성 유행어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 32,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["신난다", "아싸", "좋아"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 102,
    word: "샤갈",
    source: "초등학생 숏폼 댓글 및 게임 채팅",
    student_definition: "유명 화가의 이름을 빌려왔으나, 실제로는 거친 욕설과 '갈기다'라는 표현을 결합하여 교묘하게 필터링을 피하고 상대를 공격할 때 쓰는 위장형 비속어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 5, bullying: 4, discrimination: 1, violence: 2, grammar_destruction: 5 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["화내지 않고 말하기", "바른 표현 쓰기"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 103,
    word: "짜짜로니",
    source: "학급 단톡방 및 틱톡 댓글",
    student_definition: "라면 이름을 차용했으나 실제로는 '진짜 진짜 짜증 난다'라는 감정을 과격하고 장난스럽게 은폐하여 표현한 초등학생용 변형 은어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 3, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 44,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["정말 속상하고 짜증 나", "마음 가다듬기"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 104,
    word: "네네치킨 (~네)",
    source: "메신저 조롱성 핑퐁 대화 밈",
    student_definition: "상대방의 진지한 조언에 대답하는 척하면서 '네네'를 무한 반복하며 상대방을 비꼬고 소통을 거부하는 냉소적인 유행 대화 말투",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 4, bullying: 4, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 52,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["알겠습니다", "주의 깊게 듣겠습니다"],
    curriculum_code: "6\uad6d01-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 105,
    word: "시발비용",
    source: "SNS 및 직장인 커뮤니티 파생 밈",
    student_definition: "스트레스를 받아 홧김에 지르는 비용이라는 뜻으로, 비속어를 경제적 용어처럼 일상화하여 학생들이 욕설에 무감각해지게 만드는 잘못된 신조어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 4, bullying: 1, discrimination: 1, violence: 2, grammar_destruction: 4 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["스트레스 해소 비용", "충동구매 비용"],
    curriculum_code: "6\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 106,
    word: "롬곡옾닢",
    source: "인터넷 유머 게시판 야민정음",
    student_definition: "글자를 상하좌우로 뒤집어 보면 '폭풍눈물'이 되는 형태의 글자 파괴 유행어로, 감정 표현을 장난스러운 철자 파괴로 소모하는 밈",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["많은 눈물", "펑펑 우는 모습"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 107,
    word: "머엽",
    source: "인터넷 게임 채팅창 야민정음",
    student_definition: "'대엽' 또는 '대박'을 글자 자모 모양의 유사성을 이용해 '머엽'으로 변형해 사용하는 무분별한 한글 가독성 파괴 신조어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["대박", "굉장하다"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 108,
    word: "댕댕이",
    source: "인스타그램 및 반려동물 릴스 밈",
    student_definition: "'강아지'를 뜻하는 '멍멍이'의 글자 초성을 자모 유사성에 따라 '댕댕이'로 바꾸어 부르는 어휘로, 한글 맞춤법을 완전히 파괴하는 유행어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 32,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["강아지", "멍멍이"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 109,
    word: "네다씹",
    source: "서브컬처 커뮤니티 댓글",
    student_definition: "'네 다음 오타쿠'의 줄임말로 특정 취미나 매체에 깊게 몰두하는 친구를 오타쿠라 비하하고 또래 집단 내에서 낙인찍는 조롱성 단어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 4, bullying: 4, discrimination: 3, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 64,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["취미 존중하기", "개인 성향 인정"],
    curriculum_code: "6\uad6d01-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 110,
    word: "어또",
    source: "온라인 갈등 유머 게시판",
    student_definition: "특정 성별 집단의 감정적 대처나 행동을 지칭하며 '어머 또 저런다'는 식으로 일반화하여 세대·성별 간 조롱을 조장하는 매체 혐오 유행어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 4, bullying: 3, discrimination: 5, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["또 시작되었네", "서로 이해하기"],
    curriculum_code: "6\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 111,
    word: "급식충",
    source: "온라인 커뮤니티 및 청소년 게임 은어",
    student_definition: "학교에서 급식을 먹는 나이대인 초·중·고등학생들을 벌레(蟲)에 빗대어 낮잡아 부르는 말로, 학생 집단 전체를 모욕하는 대표적인 비하 혐오어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 5, bullying: 4, discrimination: 5, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 68,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["학생", "청소년", "또래 친구"],
    curriculum_code: "6\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 112,
    word: "버카충",
    source: "청소년 일상 줄임말",
    student_definition: "'버스 카드 충전'의 앞 글자를 딴 단순 생활 줄임말이나, 청소년 비하 어휘인 '충(蟲)' 자와 어미 발음이 동일하여 오해를 유발할 수 있는 과도한 축약어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 32,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["교통카드 충전", "버스 카드 충전"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 113,
    word: "안습",
    source: "인터넷 대화방 및 대중 매체 유행어",
    student_definition: "'안구에 습기 차다'의 줄임말로, 상대방의 아쉬운 실수나 초라한 상황을 장난스럽고 가볍게 표현하여 감정을 희화화하는 신조어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["안타깝다", "눈물이 난다", "아쉬운 상황이야"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 114,
    word: "개안습",
    source: "인터넷 게시판 댓글 및 게임 채팅",
    student_definition: "줄임말 '안습'에 비속어성 접두사인 '개-'를 결합하여, 타인의 안타까운 상황이나 실수를 극단적으로 강조하며 무안을 줄 때 사용하는 저속한 어휘",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 4, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 56,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["정말 안타깝다", "무척 아쉬운 일이다"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 115,
    word: "설설",
    source: "온라인 게임 대화창 및 숏폼 댓글",
    student_definition: "상대방의 기를 죽이거나 굴복시키기 위해 '눈치 보며 설설 기어라'라고 조롱하는 공격성 말투로, 또래 관계 내에서 심리적 우위를 점하려는 위협성 밈",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 4, bullying: 4, discrimination: 1, violence: 2, grammar_destruction: 1 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["서로 배려하다", "동등하게 대화하다"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 116,
    word: "설설봇",
    source: "인게임 매크로 채팅 및 조롱 밈",
    student_definition: "게임 실력이 미숙한 유저에게 로봇처럼 복종하고 '설설 기어 다니라'며 반복적으로 가하는 인게임 매크로형 언어폭력성 괴롭힘 밈",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 5, bullying: 5, discrimination: 1, violence: 3, grammar_destruction: 4 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["초보 유저 배려하기", "친절하게 안내하기"],
    curriculum_code: "6\uad6d01-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 117,
    word: "복세편살",
    source: "SNS 프로필 문구 및 줄임말 밈",
    student_definition: "'복잡한 세상 편하게 살자'의 줄임말로, 공동체의 문제보다 개인의 안위나 편안함을 우선하려는 성향을 가볍게 축약한 단어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 32,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["마음 편하게 살아가기", "여유로운 마음"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 118,
    word: "인증샷",
    source: "SNS 플랫폼 및 미디어 밈",
    student_definition: "자신의 행동이나 방문 사실을 사진으로 남겨 증명한다는 뜻의 대중적 유행 축약어로, 올바른 표준어인 '기록사진'이나 '확인사진'을 영문과 결합해 대체함",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["기록사진", "확인용 사진"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 119,
    word: "별창",
    source: "인터넷 방송 플랫폼 비하 댓글",
    student_definition: "인터넷 방송에서 후원 아이템을 얻기 위해 과격하거나 선정적인 행동을 하는 진행자를 성적인 비속어와 결합하여 비하하는 반인륜적 모욕 혐오어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 5, bullying: 4, discrimination: 4, violence: 2, grammar_destruction: 3 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["인터넷 방송인", "개인 크리에이터"],
    curriculum_code: "6\uad6d05-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 120,
    word: "조별과제 잔혹사",
    source: "대학 커뮤니티 파생 초등 모둠활동 밈",
    student_definition: "모둠 활동 시 참여가 저조한 팀원을 저격하고 조롱하기 위해 쓰는 유행 상황극 밈으로, 모둠 간의 신뢰와 우대를 저해할 우려가 있는 단어",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 3, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 44,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["모둠 활동의 어려움", "서로 협동하는 활동"],
    curriculum_code: "6\uad6d01-02",
    timestamp: "2026-07-11 00:12:00",
  },
  {
    id: 121,
    word: "존예",
    source: "청소년 일상 대화 및 SNS 댓글 은어",
    student_definition: "엄청나게 예쁘다는 뜻으로 쓰이지만, 앞글자 '존'은 원래 남성의 신체를 상스럽게 비하하는 심각한 욕설인 '좆'에서 온 말입니다. 뜻을 모른 채 쓰더라도 결국 상스러운 욕을 섞어 예쁘다고 말하는 꼴이 되므로 사용하지 않아야 합니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 예쁘다", "무척 아름답다"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 122,
    word: "존맛",
    source: "음식 리뷰 숏폼 및 초등학생 유행어",
    student_definition: "진짜 맛있다는 뜻으로 초등학생들이 자주 씁니다. 하지만 '존'의 진짜 어원은 어른들도 함부로 입에 담지 않는 아주 거친 욕설('좆')입니다. 맛있는 음식을 눈앞에 두고 거친 욕설을 섞어 표현하는 것은 대화의 품격을 떨어뜨리는 행동입니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["진짜 맛있다", "매우 훌륭한 맛이다"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 123,
    word: "존멋",
    source: "인스타그램 릴스 및 아이돌 팬덤 밈",
    student_definition: "정말 멋지다는 뜻의 유행어입니다. 하지만 강조하기 위해 붙인 '존'은 남성의 신체를 아주 상스럽게 이르는 비속어('좆')에서 출발했습니다. 멋진 친구나 인물을 칭찬할 때 욕설을 섞어 칭찬하는 것은 오히려 상대방을 존중하지 않는 예의 없는 말투입니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 멋지다", "굉장히 훌륭하다"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 124,
    word: "존못",
    source: "온라인 게임 채팅 및 또래 비하 대화",
    student_definition: "진짜 못생겼거나 실력이 형편없다며 친구를 놀리는 말입니다. 아주 거칠고 상스러운 욕설인 '좆'에 '못하다'를 합친 말로, 상대방의 외모나 능력을 욕설로 짓밟아 큰 상처를 주는 나쁜 비하 단어이므로 절대로 쓰면 안 됩니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 5, bullying: 5, discrimination: 4, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 80,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["외모 비하 금지", "실력이 조금 서툴다"],
    curriculum_code: "6\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 125,
    word: "존맛탱 (JMT)",
    source: "인터넷 먹방 자막 및 SNS 해시태그",
    student_definition: "존맛을 더 늘리거나 영어 앞글자만 따서 'JMT'라고 예쁘게 포장해 쓰는 밈입니다. 영어로 숨겨놓았지만 가장 밑바탕에는 남성의 신체를 상스럽게 욕하는 비속어 '좆'이 들어있으므로, 유행을 따라 하듯 무분별하게 쓰는 것을 멈춰야 합니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["무척 맛있다", "아주 맛이 좋다"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 126,
    word: "존귀",
    source: "반려동물 쇼츠 영상 자막 및 댓글",
    student_definition: "엄청나게 귀엽다는 뜻의 축약어입니다. 국어사전의 '존귀(尊貴: 존경스럽고 귀하다)'와 소리는 같지만, 학생들이 쓰는 밈은 상스러운 욕설('좆')과 '귀엽다'를 합친 한글 파괴 은어입니다. 예쁘고 사랑스러운 대상을 향해 욕을 섞어 부르는 모순된 표현입니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 귀엽다", "아주 사랑스럽다"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 127,
    word: "존잼",
    source: "웹툰 베스트 댓글 및 학교 메신저",
    student_definition: "진짜 재미있다는 뜻으로 널리 쓰이지만, 재미라는 단어 앞에 붙은 '존'은 상스러운 비속어 욕설('좆')의 형태를 바꾼 것입니다. 우리가 일상에서 재미있는 경험을 이야기할 때조차 무의식중에 상스러운 욕설을 섞어 쓰지 않도록 조심해야 합니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 재미있다", "무척 흥미진진하다"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 128,
    word: "존노잼 / 존노",
    source: "유튜브 쇼츠 댓글 창",
    student_definition: "상스러운 욕설에서 온 '존'에 영어의 부정(No)과 재미를 합친 정체불명의 유행어입니다. 한글 표준어의 아름다움을 심각하게 깨뜨릴 뿐만 아니라, 바탕에 욕설을 깔고 있어 듣는 사람에게 불쾌감을 주는 좋지 못한 말장난 밈입니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 3, bullying: 2, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["정말 재미없다", "조금 지루하다"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 129,
    word: "존버",
    source: "인터넷 주식 방송 및 청소년 게임 채팅",
    student_definition: "끝까지 악착같이 버틴다는 뜻으로 어른들도 가끔 쓰는 유행어입니다. 하지만 이 단어의 어원은 거친 비속어 욕설('좆')과 '버티기'가 합쳐진 아주 상스러운 조합입니다. 힘든 일을 끈기 있게 참아낼 때는 욕설 대신 '인내'나 '노력' 같은 고운 표현을 써야 합니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 3, bullying: 1, discrimination: 1, violence: 2, grammar_destruction: 5 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["끝까지 버티기", "끝까지 힘내기"],
    curriculum_code: "6\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 130,
    word: "존똑",
    source: "인스타그램 육아 툰 및 일상 유행어",
    student_definition: "외모나 행동이 진짜 똑같이 닮았다는 뜻의 유행어입니다. 강조의 의미로 쓰인 '존'은 남성의 신체를 낮잡아 이르는 욕설('좆')에서 유래했으므로, 부모님이나 친구, 소중한 사람과 닮았다는 아름다운 이야기를 나눌 때는 '똑 닮았다'라는 고운 표준어를 사용하는 것이 맞습니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 똑같다", "똑 닮았다"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 131,
    word: "존싫",
    source: "학급 단톡방 감정 표현 밈",
    student_definition: "진짜 끔찍하게 싫다는 거부감을 과격하게 표현한 단어입니다. 상스러운 욕설에서 온 '존'과 '싫다'를 결합한 형태로, 단어의 모양 자체도 예쁘지 않을뿐더러 자신의 부정적인 감정을 욕설에 기대어 쏟아내기 때문에 듣는 친구에게 큰 거부감과 상처를 줍니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 4, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 56,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["정말 싫어", "나는 내키지 않아"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 132,
    word: "존좋",
    source: "인스타 스토리 리액션 밈",
    student_definition: "엄청나게 마음에 들고 좋다는 뜻을 속되게 줄여 쓴 단어입니다. '존'의 밑바탕은 거친 비속어 욕설('좆')이므로, 자신이 느끼는 행복하고 좋은 기분을 이렇게 상스러운 어원을 가진 축약어로 짓밟지 말고 '무척 마음에 들어' 같은 깨끗한 우리말로 표현해 보세요.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 좋다", "무척 마음에 든다"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 133,
    word: "존웃",
    source: "유튜브 쇼츠 리액션 자막",
    student_definition: "배가 아플 정도로 진짜 웃기다는 뜻의 인터넷 밈입니다. 그러나 강조를 위해 붙인 '존'은 남성의 특정 부위를 상스럽게 부르는 비속어('좆')가 변형된 것입니다. 웃음이라는 순수하고 즐거운 감정 표현에 나쁜 비속어의 흔적을 묻혀 쓰는 것은 바람직하지 않습니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 웃기다", "무척 재미있다"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 134,
    word: "존나",
    source: "청소년 일상 대화 및 온라인 비속어",
    student_definition: "'존-'으로 시작하는 모든 유행어의 엄마가 되는 아주 거칠고 상스러운 원본 욕설입니다. 원래는 남성의 몸을 아주 천하게 비하하는 뜻에서 나온 심각한 비속어이므로, 습관적으로 문장마다 이 말을 붙여 쓰는 버릇은 부끄러운 언어 행위이며 반드시 고쳐야 합니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 5, bullying: 2, discrimination: 1, violence: 2, grammar_destruction: 5 },
    total_harmful_score: 60,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["매우", "엄청나게", "진짜"],
    curriculum_code: "6\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 135,
    word: "핵존맛",
    source: "식당 홍보 인스타그램 해시태그",
    student_definition: "폭탄을 뜻하는 '핵'과 비속어 줄임말인 '존맛'을 겹쳐 써서 자극성을 끝까지 높인 상업용 유행어입니다. 뜻을 더 강하게 만들기 위해 비속어('좆')에 파괴적 단어를 주렁주렁 매단 모습으로, 한글의 올바른 부사 수식 형식을 어지럽히는 어휘입니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 3, grammar_destruction: 5 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["꿀맛", "환상적인 맛", "정말 맛있다"],
    curriculum_code: "6\uad6d05-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 136,
    word: "존귀탱",
    source: "반려동물 및 아기 영상 릴스 댓글",
    student_definition: "진짜 귀엽다는 뜻의 '존귀' 뒤에 귀여운 느낌의 글자 '-탱'을 한 번 더 붙여 쓰는 은어입니다. 아무리 귀여운 척 포장을 해도 바탕 어원이 거친 비속어 욕설('좆')이라는 사실은 변하지 않으므로, 소중한 아기나 귀여운 동물에게 어울리지 않는 잘못된 단어입니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 40,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 사랑스럽다", "무척 귀엽다"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 137,
    word: "존힘",
    source: "온라인 게임 및 학원 생활 한탄 대화",
    student_definition: "진짜 힘들어 죽겠다는 짜증 섞인 마음을 속되게 줄여 표현한 유행어입니다. 상스러운 욕설에서 온 '존'을 힘든 감정 표현 앞에 굳이 붙여서 쏟아내기 때문에, 대화의 전반적인 분위기를 거칠게 만들고 자신의 언어 습관을 스스로 오염시키게 됩니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 3, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 44,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["정말 무겁고 힘들다", "무척 지친다"],
    curriculum_code: "6\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 138,
    word: "존무",
    source: "인터넷 공포 만화 및 쇼츠 영상 댓글",
    student_definition: "진짜 무섭다는 공포심을 저속하게 축약해 사용하는 유행어입니다. 강조어로 쓰인 '존'의 뿌리가 거친 비속어 욕설('좆')임을 안다면, 오싹하고 무서운 상황에서 '소름 돋는다'라거나 '정말 무섭다'라는 깨끗하고 올바른 형용사를 두고 굳이 욕설 밈을 쓸 필요가 없습니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 3, grammar_destruction: 5 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["정말 무섭다", "오싹하다"],
    curriculum_code: "4\uad6d05-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 139,
    word: "존느",
    source: "온라인 커뮤니티 게시판 우회 비속어",
    student_definition: "상스러운 원본 욕설인 '존나'를 치면 게임이나 사이트에서 필터링 시스템에 의해 차단당하니까, 글자 모양과 발음을 '존느'로 살짝 꼼수를 부려 바꾸어 쓰는 비겁한 비속 우회어입니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 4, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 48,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["대단히", "무척", "참으로"],
    curriculum_code: "6\uad6d05-02",
    timestamp: "2026-07-11 00:16:00",
  },
  {
    id: 140,
    word: "존당",
    source: "초등 여학생 메신저 이모티콘 자막",
    student_definition: "비속어 파생 은어인 '존귀탱'을 '존당'으로 한 글자 더 쪼개서 부르는 말장난 변형 신조어입니다. 귀여운 말 같지만 필터링을 거치며 원형 욕설의 흔적이 숨어 있어, 본래 나쁜 욕설 바탕에서 시작된 말임을 잊게 만드는 위험성이 있습니다.",
    suggested_by: "교사 프리셋",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["귀요미", "사랑둥이"],
    curriculum_code: "4\uad6d01-02",
    timestamp: "2026-07-11 00:16:00",
  },
];


export const MEME_TRIGGERS = ["어쩔티비", "저쩔티비", "누칼협", "핑프", "억텐", "찐따", "노잼", "꺼져", "존버", "ㅅㅂ", "ㅄ", "ㅈㄴ", "빡친다", "개짜증"];

// Dynamic feedback arrays keyed by attempt count (0-based).
export const MEME_FEEDBACK = [
  '방금 쓴 "{word}"는 이 상황에 어울리지 않는 표현이에요. 아래 💡 가이드를 참고해서 다시 써볼래요?',
  '"{word}" 같은 유행어 대신, 상대방을 존중하는 우리말로 바꿔볼까요? 예: "{hint}"',
  '선생님은 너의 바른 모습을 기대하고 있어요. 이번엔 "죄송합니다" 또는 존댓말로 시작하는 문장을 완성해 보세요.',
];

export const SHORT_FEEDBACK = [
  '문장이 조금 짧아요. 상황을 담아 조금 더 자세히 말해볼까요?',
  '누가·언제·왜를 담아 완성된 문장으로 답해 보세요. 예: "{hint}"',
  '가이드의 예시 문장을 그대로 따라 써 봐도 좋아요. 함께 연습해요! 예: "{hint}"',
];

export const IMPOLITE_FEEDBACK = [
  '조금 더 예의를 담은 말투가 필요해요. 존댓말로 다시 표현해 볼까요?',
  '상대의 마음을 생각하며, 부드러운 표현으로 바꿔 볼까요? 예: "{hint}"',
  '이번에는 가이드를 그대로 참고해서 마무리해 보세요. 예: "{hint}"',
];

export const PRAISE_FEEDBACK = [
  '고마워요! 그렇게 예의 바르게 말해줘서 마음이 따뜻해졌어요. ✨',
  '멋진 표현이에요! 상황과 예절이 딱 맞았어요. 🌱',
  '와, 정말 훌륭한 답이에요. 우리 반 언어 기상도가 맑아졌어요! ☀️',
];

export type Scenario = {
  id: string;
  npc: string;
  emoji: string;
  opening: string;
  goodExampleHint: string;
  guide: string;
  stages: ScenarioStage[];
  completeBadge?: string;
};

export type ScenarioStage = {
  /** NPC opening line for this stage */
  npc: string;
  /** Guide box heading & instruction for the student */
  guide: string;
  /** Bold example the student should model */
  hint: string;
  /** Praise line NPC sends when student clears this stage */
  praise: string;
};

export const SCENARIOS: Scenario[] = [
  {
    id: "teacher-late",
    npc: "담임 선생님",
    emoji: "👩‍🏫",
    opening: "○○아, 오늘 왜 지각했니? 무슨 일 있었어?",
    goodExampleHint: "죄송합니다. 늦잠을 자서 늦었습니다. 앞으로 조심하겠습니다.",
    guide: "선생님께 죄송한 마음을 담아 상황을 설명해 보세요. '죄송합니다'로 문장을 시작해 볼까요?",
    completeBadge: "🎖️ 예절 배지 획득 · 담임 선생님",
    stages: [
      {
        npc: "○○아, 오늘 왜 지각했니? 무슨 일 있었어?",
        guide: "1단계 · 지각한 이유를 사과와 함께 설명해요. '죄송합니다'로 시작해요.",
        hint: "죄송합니다. 늦잠을 자서 늦었습니다.",
        praise: "그렇게 솔직히 말해줘서 고마워. 이유를 잘 설명했구나.",
      },
      {
        npc: "그렇구나. 그럼 앞으로 어떻게 하면 좋을까?",
        guide: "2단계 · 앞으로 어떻게 실천할지 구체적인 다짐을 약속해요.",
        hint: "앞으로는 알람을 두 개 맞추고 일찍 자겠습니다.",
        praise: "구체적인 계획이 정말 훌륭해! 선생님도 응원할게.",
      },
      {
        npc: "좋아. 마지막으로 이 약속을 지킬 수 있겠니?",
        guide: "3단계 · 다짐을 확인하며 정중하게 마무리 인사를 해요.",
        hint: "네, 꼭 지키겠습니다. 감사합니다.",
        praise: "🎉 정말 멋진 대화였어. 너의 진심이 잘 느껴졌단다. 대화 종료!",
      },
    ],
  },
  {
    id: "parent-phone",
    npc: "엄마",
    emoji: "👩",
    opening: "핸드폰만 보고 있네? 숙제는 다 했어?",
    goodExampleHint: "죄송해요, 조금만 더 보고 바로 숙제할게요.",
    guide: "부모님을 존중하는 마음으로, 앞으로 어떻게 할지 계획을 담아 답해 보세요.",
    completeBadge: "🎖️ 예절 배지 획득 · 엄마와의 대화",
    stages: [
      {
        npc: "핸드폰만 보고 있네? 숙제는 다 했어?",
        guide: "1단계 · 사실대로 이실직고하고 죄송한 마음을 담아 답해요.",
        hint: "죄송해요, 아직 다 못 했어요. 지금 시작할게요.",
        praise: "솔직히 말해줘서 고마워. 엄마도 마음이 놓이네.",
      },
      {
        npc: "그럼 앞으로 핸드폰 사용은 어떻게 조절할래?",
        guide: "2단계 · 알람 맞추기 등 스스로 지킬 수 있는 대안을 제안해요.",
        hint: "숙제 알람을 맞춰서 30분만 쓰고 바로 숙제할게요.",
        praise: "스스로 방법을 찾다니 정말 대견하구나.",
      },
      {
        npc: "그래, 우리 아들/딸 참 든든하네. 오늘도 힘내자!",
        guide: "3단계 · 응원에 감사 인사를 담아 대화를 정리해요.",
        hint: "네, 응원해줘서 고마워요. 잘 해볼게요!",
        praise: "🎉 따뜻한 대화 고마워. 우리 가족의 하루가 밝아졌어. 대화 종료!",
      },
    ],
  },
  {
    id: "new-friend",
    npc: "처음 본 친구",
    emoji: "🧒",
    opening: "안녕! 나는 옆 반 하늘이야. 너 이름이 뭐야?",
    goodExampleHint: "안녕! 나는 ○○이야. 만나서 반가워.",
    guide: "밝게 인사한 뒤, 자신의 이름을 소개하고 반가운 마음을 표현해 보세요.",
    completeBadge: "🎖️ 예절 배지 획득 · 새 친구 사귀기",
    stages: [
      {
        npc: "저기, 운동장이 어느 쪽이야? 나 오늘 전학 왔거든.",
        guide: "1단계 · 친절하게 방향을 알려주고 도움을 줘요.",
        hint: "안녕! 운동장은 저쪽 계단으로 내려가면 있어. 같이 갈래?",
        praise: "고마워! 친절히 알려줘서 마음이 놓여.",
      },
      {
        npc: "정말 고마워! 근데 네 이름이 뭐야? 친구가 되고 싶어.",
        guide: "2단계 · 밝게 이름을 소개하고 친구 제안을 수락해요.",
        hint: "나는 ○○이야. 좋아, 우리 친구하자!",
        praise: "와, 반가워! 좋은 친구가 될 것 같아.",
      },
      {
        npc: "그럼 내일 쉬는 시간에 같이 놀자! 어때?",
        guide: "3단계 · 약속을 반갑게 수락하며 환영 인사를 해요.",
        hint: "좋아! 내일 쉬는 시간에 우리 반 앞에서 만나자.",
        praise: "🎉 새 친구가 생겨서 정말 기뻐! 대화 종료!",
      },
    ],
  },
  {
    id: "librarian",
    npc: "도서관 선생님",
    emoji: "📚",
    opening: "얘야, 도서관에서는 조용히 해야 한단다.",
    goodExampleHint: "네, 죄송합니다. 조용히 하겠습니다.",
    guide: "규칙을 지키지 못한 점을 인정하고 앞으로의 행동을 약속하는 문장으로 답해 보세요.",
    completeBadge: "🎖️ 매너 배지 획득 · 도서관 예절",
    stages: [
      {
        npc: "얘야, 도서관에서 조금 시끄러웠단다. 어떻게 해야 할까?",
        guide: "1단계 · 소란을 피운 행동을 즉시 사과해요.",
        hint: "죄송합니다. 앞으로 조용히 하겠습니다.",
        praise: "바로 사과해줘서 고마워. 마음이 느껴지는구나.",
      },
      {
        npc: "그런데 책도 제자리에 두지 않았더구나. 어떻게 하면 좋겠니?",
        guide: "2단계 · 정리하지 않은 점을 인정하고 해결 방법을 제시해요.",
        hint: "제가 정리하지 않았어요. 지금 바로 제자리에 꽂아둘게요.",
        praise: "책임감이 정말 훌륭하구나. 도서관이 밝아졌어.",
      },
      {
        npc: "정말 훌륭한 태도야! 매너 배지를 줄게. 앞으로도 잘 부탁해!",
        guide: "3단계 · 감사 인사와 함께 앞으로의 다짐을 짧게 전해요.",
        hint: "감사합니다! 앞으로 규칙을 잘 지킬게요.",
        praise: "🎉 매너 배지 획득! 우리 도서관의 자랑이야. 대화 종료!",
      },
    ],
  },
];

export type QuizItem = {
  q: string;
  choices: string[];
  answer: number;
  explain: string;
};

export const QUIZZES: QuizItem[] = [
  {
    q: "'어쩔티비'를 바른 말로 바꾸면?",
    choices: ["네 생각을 존중해", "저리 가라", "됐거든", "몰라"],
    answer: 0,
    explain: "상대방을 존중하는 말로 바꾸면 대화가 부드러워져요.",
  },
  {
    q: "'누칼협'에 담긴 태도는?",
    choices: ["공감과 위로", "친구를 놀리고 비웃음", "칭찬과 격려", "사과와 반성"],
    answer: 1,
    explain: "상대의 힘든 상황을 조롱하는 표현으로 사용을 피해야 합니다.",
  },
  {
    q: "'핑프'와 반대되는 좋은 태도는?",
    choices: ["아무 것도 안 하기", "스스로 찾아보고 질문하기", "친구 답 베끼기", "선생님만 믿기"],
    answer: 1,
    explain: "먼저 스스로 찾아본 뒤 질문하는 태도가 바람직합니다.",
  },
  {
    q: "친구가 실수했을 때 바른 말은?",
    choices: ["개웃겨 ㅋㅋ", "괜찮아, 누구나 실수할 수 있어", "핑프 아니야?", "노잼"],
    answer: 1,
    explain: "친구를 배려하는 말은 관계를 따뜻하게 만듭니다.",
  },
  {
    q: "'억텐'의 뜻은?",
    choices: ["억지로 밝은 척", "억울한 텐션", "억센 팀장", "억센 텐트"],
    answer: 0,
    explain: "'억지 텐션'의 줄임말이에요.",
  },
];