import type { DictEntry } from "./literacy-types";

export const SEED_DICT: DictEntry[] = [
  {
    id: 1,
    word: "스타벅스 가야지",
    student_definition: "스타벅스가 5.18 관련 행사(탱크데이)를 했다는 허위 사실과 결합하여, 광주 지역과 5.18 민주화운동의 희생자들을 조롱하기 위해 사용된 심각한 지역 비하 혐오 표현",
    suggested_by: "교사 프리셋",
    source: "온라인 커뮤니티 및 학생 야구 비하 논란",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 5, grammar_destruction: 1 },
    total_harmful_score: 84,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["바른 표현 사용", "역사적 사실 존중"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 2,
    word: "탱크데이",
    student_definition: "5.18 민주화운동 당시 계엄군의 탱크 진압을 희화화하고 희생자들을 모욕하기 위해 만들어진 반인륜적 은어",
    suggested_by: "교사 프리셋",
    source: "일간베스트 등 극우 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 5, grammar_destruction: 2 },
    total_harmful_score: 88,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["5.18 민주화운동", "역사적 아픔 공감"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 3,
    word: "운지",
    student_definition: "특정 전임 대통령의 서거를 비하하고 조롱하기 위해 만들어진 대표적인 일베 발 혐오 신조어",
    suggested_by: "교사 프리셋",
    source: "일간베스트 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 4, grammar_destruction: 3 },
    total_harmful_score: 88,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["추락하다", "떨어지다"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 4,
    word: "홍어",
    student_definition: "호남 지역 주민들을 특정 수산물에 빗대어 비하하고 차별하기 위해 사용하는 악의적인 지역 혐오 단어",
    suggested_by: "교사 프리셋",
    source: "일간베스트 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 2, grammar_destruction: 1 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["호남 지역민", "차별 없는 언어 사용"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 5,
    word: "이기야",
    student_definition: "영남 지역 방언을 왜곡하여 특정 정치인을 조롱하고 커뮤니티 소속감을 드러내기 위해 사용하는 혐오 코드 어미",
    suggested_by: "교사 프리셋",
    source: "일간베스트 커뮤니티",
    evaluations: { aggression: 4, bullying: 3, discrimination: 5, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["표준어 어미 사용", "~이구나"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 6,
    word: "노노체 (~노)",
    student_definition: "문맥에 맞지 않게 끝에 '노'를 붙여 특정 대상을 풍자하는 일베의 대표적인 조롱성 말투",
    suggested_by: "교사 프리셋",
    source: "일간베스트 커뮤니티",
    evaluations: { aggression: 3, bullying: 3, discrimination: 5, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["~했니?", "~했어?"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 7,
    word: "누칼협",
    student_definition: "누가 칼 들고 협박함의 줄임말로, 타인의 힘든 상황에 공감하지 않고 조롱하는 차가운 매체 언어",
    suggested_by: "교사 프리셋",
    source: "온라인 게임 커뮤니티",
    evaluations: { aggression: 5, bullying: 4, discrimination: 2, violence: 4, grammar_destruction: 4 },
    total_harmful_score: 76,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["많이 힘들었겠구나", "속상하겠다"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 8,
    word: "알빠노",
    student_definition: "내가 알 바 아니라는 뜻에 일베식 어미를 붙여 타인의 고통에 극단적으로 무관심을 표하는 언어",
    suggested_by: "교사 프리셋",
    source: "인터넷 방송",
    evaluations: { aggression: 4, bullying: 4, discrimination: 4, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["상관없어", "내 관여 밖의 일이야"],
    curriculum_code: "6국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 9,
    word: "피싸개",
    student_definition: "여성의 생리 현상을 비하하고 여성 전체에 대한 극단적 혐오를 드러내는 폭력적인 차별 용어",
    suggested_by: "교사 프리셋",
    source: "남초 온라인 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 3, grammar_destruction: 2 },
    total_harmful_score: 80,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["여성", "양성평등 언어 사용"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 10,
    word: "한남 / 한녀",
    student_definition: "한국 남성/여성을 벌레 등에 빗대어 성별 간의 혐오와 대립을 조장하는 차별적 비하 발언",
    suggested_by: "교사 프리셋",
    source: "성별 갈등 커뮤니티",
    evaluations: { aggression: 4, bullying: 4, discrimination: 5, violence: 2, grammar_destruction: 2 },
    total_harmful_score: 68,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["한국 남성", "한국 여성"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 11,
    word: "틀딱",
    student_definition: "노인들의 틀니 소리를 빗대어 고령층을 혐오하고 세대 갈등을 유발하는 노인 비하 단어",
    suggested_by: "교사 프리셋",
    source: "온라인 커뮤니티",
    evaluations: { aggression: 5, bullying: 4, discrimination: 5, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["어르신", "노인"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 12,
    word: "맘충",
    student_definition: "아이를 키우는 어머니들을 벌레에 빗대어 비하하고 혐오하는 차별적 조롱 표현",
    suggested_by: "교사 프리셋",
    source: "온라인 커뮤니티",
    evaluations: { aggression: 5, bullying: 5, discrimination: 5, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 72,
    status: "approved",
    grade: "위험/사용 금지",
    alternatives: ["어머니", "학부모"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 13,
    word: "잼민이",
    student_definition: "어린이나 초등학생이 공공예절을 지키지 않는다는 편견을 씌워 연령층을 비하하는 단어",
    suggested_by: "교사 프리셋",
    source: "인터넷 방송",
    evaluations: { aggression: 3, bullying: 4, discrimination: 4, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 60,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["어린이", "초등학생"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 14,
    word: "퐁퐁남",
    student_definition: "결혼 생활을 하는 남성을 경제적 착취의 피해자로 규정하며 여성 혐오적 시각을 드러내는 단어",
    suggested_by: "교사 프리셋",
    source: "남초 온라인 커뮤니티",
    evaluations: { aggression: 4, bullying: 4, discrimination: 5, violence: 1, grammar_destruction: 2 },
    total_harmful_score: 64,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["기혼 남성", "남편"],
    curriculum_code: "6국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 15,
    word: "어쩔티비",
    student_definition: "상대방의 의견이나 조언을 무시하고 대화를 단절시키기 위해 사용하는 예의 없는 유행어",
    suggested_by: "교사 프리셋",
    source: "유튜브 콘텐츠",
    evaluations: { aggression: 4, bullying: 3, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 56,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["그렇구나", "내 생각은 달라"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 16,
    word: "핑프",
    student_definition: "스스로 검색하지 않고 남에게 의존하는 사람을 조롱하여 무안을 주는 공격적 표현",
    suggested_by: "교사 프리셋",
    source: "대학 및 커뮤니티 게시판",
    evaluations: { aggression: 3, bullying: 4, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 52,
    status: "approved",
    grade: "주의/경고",
    alternatives: ["의존적인 습관", "스스로 찾아보기"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 17,
    word: "킹받네",
    student_definition: "화가 나거나 어이없는 상황을 문법을 파괴하여 자극적으로 표현하는 일상 속 비속어",
    suggested_by: "교사 프리셋",
    source: "인터넷 방송",
    evaluations: { aggression: 2, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 4 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["정말 화가 나", "어처구니가 없어"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 18,
    word: "개이득",
    student_definition: "접두사 개-를 남용하여 큰 이익을 보았음을 강조하는 상스러운 문법 파괴 표현",
    suggested_by: "교사 프리셋",
    source: "온라인 커뮤니티",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 5 },
    total_harmful_score: 36,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["큰 이익이야", "정말 잘됐어"],
    curriculum_code: "4국01-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 19,
    word: "중꺾마",
    student_definition: "중요한 것은 꺾이지 않는 마음의 줄임말로 긍정적 의미이나, 과도한 줄임말 사용에 해당함",
    suggested_by: "교사 프리셋",
    source: "e스포츠 보도",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["포기하지 않는 마음", "끈기"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
  {
    id: 20,
    word: "혜자스럽다",
    student_definition: "가성비가 훌륭하다는 의미로 특정 인물의 이름을 차용하여 만들어진 신조어",
    suggested_by: "교사 프리셋",
    source: "편의점 상품 밈",
    evaluations: { aggression: 1, bullying: 1, discrimination: 1, violence: 1, grammar_destruction: 3 },
    total_harmful_score: 28,
    status: "approved",
    grade: "안전/순화 필요",
    alternatives: ["가격 대비 성능이 좋다", "푸짐하다"],
    curriculum_code: "4국05-02",
    timestamp: "2026-07-10 23:56:00",
  },
];


export const MEME_TRIGGERS = ["어쩔티비", "저쩔티비", "누칼협", "핑프", "억텐", "찐따", "노잼", "꺼져", "존버", "ㅅㅂ", "ㅄ", "ㅈㄴ", "빡친다", "개짜증"];

// Dynamic feedback arrays keyed by attempt count (0-based).
export const MEME_FEEDBACK = [
  '방금 쓴 "{word}"는 이 상황에 어울리지 않는 표현이에요. 아래 💡 가이드를 참고해서 다시 써볼래요?',
  '"{word}" 같은 유행어 대신, 상대방을 존중하는 우리말로 바꿔볼까요? 예: "{hint}"',
  '선생님은 너의 바른 모습을 기대하고 있어요. 이번엔 "죄송합니다" 또는 존댓말로 시작하는 문장을 완성해 보세요.',
];

export const SHORT_FEEDBACK = [
  '문장이 조금 짧아요. 상황을 담아 조금 더 자세히 말해볼까요?',
  '누가·언제·왜를 담아 완성된 문장으로 답해 보세요. 예: "{hint}"',
  '가이드의 예시 문장을 그대로 따라 써 봐도 좋아요. 함께 연습해요! 예: "{hint}"',
];

export const IMPOLITE_FEEDBACK = [
  '조금 더 예의를 담은 말투가 필요해요. 존댓말로 다시 표현해 볼까요?',
  '상대의 마음을 생각하며, 부드러운 표현으로 바꿔 볼까요? 예: "{hint}"',
  '이번에는 가이드를 그대로 참고해서 마무리해 보세요. 예: "{hint}"',
];

export const PRAISE_FEEDBACK = [
  '고마워요! 그렇게 예의 바르게 말해줘서 마음이 따뜻해졌어요. ✨',
  '멋진 표현이에요! 상황과 예절이 딱 맞았어요. 🌱',
  '와, 정말 훌륭한 답이에요. 우리 반 언어 기상도가 맑아졌어요! ☀️',
];

export type Scenario = {
  id: string;
  npc: string;
  emoji: string;
  opening: string;
  goodExampleHint: string;
  guide: string;
};

export const SCENARIOS: Scenario[] = [
  {
    id: "teacher-late",
    npc: "담임 선생님",
    emoji: "👩‍🏫",
    opening: "○○아, 오늘 왜 지각했니? 무슨 일 있었어?",
    goodExampleHint: "죄송합니다. 늦잠을 자서 늦었습니다. 앞으로 조심하겠습니다.",
    guide: "선생님께 죄송한 마음을 담아 상황을 설명해 보세요. '죄송합니다'로 문장을 시작해 볼까요?",
  },
  {
    id: "parent-phone",
    npc: "엄마",
    emoji: "👩",
    opening: "핸드폰만 보고 있네? 숙제는 다 했어?",
    goodExampleHint: "죄송해요, 조금만 더 보고 바로 숙제할게요.",
    guide: "부모님을 존중하는 마음으로, 앞으로 어떻게 할지 계획을 담아 답해 보세요.",
  },
  {
    id: "new-friend",
    npc: "처음 본 친구",
    emoji: "🧒",
    opening: "안녕! 나는 옆 반 하늘이야. 너 이름이 뭐야?",
    goodExampleHint: "안녕! 나는 ○○이야. 만나서 반가워.",
    guide: "밝게 인사한 뒤, 자신의 이름을 소개하고 반가운 마음을 표현해 보세요.",
  },
  {
    id: "librarian",
    npc: "도서관 선생님",
    emoji: "📚",
    opening: "얘야, 도서관에서는 조용히 해야 한단다.",
    goodExampleHint: "네, 죄송합니다. 조용히 하겠습니다.",
    guide: "규칙을 지키지 못한 점을 인정하고 앞으로의 행동을 약속하는 문장으로 답해 보세요.",
  },
];

export type QuizItem = {
  q: string;
  choices: string[];
  answer: number;
  explain: string;
};

export const QUIZZES: QuizItem[] = [
  {
    q: "'어쩔티비'를 바른 말로 바꾸면?",
    choices: ["네 생각을 존중해", "저리 가라", "됐거든", "몰라"],
    answer: 0,
    explain: "상대방을 존중하는 말로 바꾸면 대화가 부드러워져요.",
  },
  {
    q: "'누칼협'에 담긴 태도는?",
    choices: ["공감과 위로", "친구를 놀리고 비웃음", "칭찬과 격려", "사과와 반성"],
    answer: 1,
    explain: "상대의 힘든 상황을 조롱하는 표현으로 사용을 피해야 합니다.",
  },
  {
    q: "'핑프'와 반대되는 좋은 태도는?",
    choices: ["아무 것도 안 하기", "스스로 찾아보고 질문하기", "친구 답 베끼기", "선생님만 믿기"],
    answer: 1,
    explain: "먼저 스스로 찾아본 뒤 질문하는 태도가 바람직합니다.",
  },
  {
    q: "친구가 실수했을 때 바른 말은?",
    choices: ["개웃겨 ㅋㅋ", "괜찮아, 누구나 실수할 수 있어", "핑프 아니야?", "노잼"],
    answer: 1,
    explain: "친구를 배려하는 말은 관계를 따뜻하게 만듭니다.",
  },
  {
    q: "'억텐'의 뜻은?",
    choices: ["억지로 밝은 척", "억울한 텐션", "억센 팀장", "억센 텐트"],
    answer: 0,
    explain: "'억지 텐션'의 줄임말이에요.",
  },
];